CORENAME: GRUS # chip core name
PB_FILE: mnist_with_ckpt.pb # input pb file name
OUTPUT_FILE: model.h # output NPU file name
NPU_UNIT: NPU32 # NPU MAC type
COMPRESS: true # compress FC weight
CONV2D_COMPRESS: true # compress Conv2D weight
OUTPUT_TYPE: c_code # output NPU file format
INPUT_OPS:
        input_x: [1, 784] # input node name and shape
OUTPUT_OPS: [result] # output node name

